name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build eksec
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build eksec
      run: make build

  test:
    name: Test eksec
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Run eksec tests
      run: make test

  lint:
    name: Lint eksec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Install Go tools
      run: |
        go install github.com/segmentio/golines@latest
        go install golang.org/x/tools/cmd/goimports@latest
        
    - name: Run eksec linting  
      run: |
        goimports -d .
        golines --max-len=120 --dry-run .
        
    - name: Run golangci-lint on eksec
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: --timeout=5m